# Generated by Django 4.0.4 on 2023-01-03 17:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_name', models.CharField(max_length=64)),
                ('category_desc', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Record',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('record_date', models.DateTimeField()),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='recordings.category')),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('height', models.FloatField()),
                ('weight', models.FloatField()),
                ('birthdate', models.DateField(default='2000-01-01')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Record_Data',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gyro_x', models.DecimalField(decimal_places=9, max_digits=13)),
                ('gyro_y', models.DecimalField(decimal_places=9, max_digits=13)),
                ('gyro_z', models.DecimalField(decimal_places=9, max_digits=13)),
                ('accel_x', models.DecimalField(decimal_places=9, max_digits=13)),
                ('accel_y', models.DecimalField(decimal_places=9, max_digits=13)),
                ('accel_z', models.DecimalField(decimal_places=9, max_digits=13)),
                ('time', models.IntegerField()),
                ('record', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='recordings.record')),
            ],
        ),
        migrations.AddField(
            model_name='record',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='recordings.user'),
        ),
    ]
