# Generated by Django 4.1.6 on 2023-04-25 21:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('recordings', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Record_Data_Extra',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gyro_x', models.DecimalField(decimal_places=9, max_digits=13)),
                ('gyro_y', models.DecimalField(decimal_places=9, max_digits=13)),
                ('gyro_z', models.DecimalField(decimal_places=9, max_digits=13)),
                ('accel_x', models.DecimalField(decimal_places=9, max_digits=13)),
                ('accel_y', models.DecimalField(decimal_places=9, max_digits=13)),
                ('accel_z', models.DecimalField(decimal_places=9, max_digits=13)),
                ('magnet_x', models.DecimalField(decimal_places=9, max_digits=13)),
                ('magnet_y', models.DecimalField(decimal_places=9, max_digits=13)),
                ('magnet_z', models.DecimalField(decimal_places=9, max_digits=13)),
                ('temp', models.DecimalField(decimal_places=2, max_digits=5)),
                ('pressure', models.DecimalField(decimal_places=6, max_digits=13)),
                ('record', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='recordings.record')),
            ],
        ),
    ]
