# Generated by Django 4.0.4 on 2023-01-03 17:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recordings', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='record_data',
            name='time',
            field=models.PositiveBigIntegerField(),
        ),
    ]
