# Generated by Django 4.1.6 on 2023-05-09 16:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recordings', '0002_record_data_extra'),
    ]

    operations = [
        migrations.AlterField(
            model_name='record_data',
            name='accel_x',
            field=models.DecimalField(decimal_places=9, max_digits=13, null=True),
        ),
        migrations.AlterField(
            model_name='record_data',
            name='accel_y',
            field=models.DecimalField(decimal_places=9, max_digits=13, null=True),
        ),
        migrations.AlterField(
            model_name='record_data',
            name='accel_z',
            field=models.DecimalField(decimal_places=9, max_digits=13, null=True),
        ),
        migrations.AlterField(
            model_name='record_data',
            name='gyro_x',
            field=models.DecimalField(decimal_places=9, max_digits=13, null=True),
        ),
        migrations.AlterField(
            model_name='record_data',
            name='gyro_y',
            field=models.DecimalField(decimal_places=9, max_digits=13, null=True),
        ),
        migrations.AlterField(
            model_name='record_data',
            name='gyro_z',
            field=models.DecimalField(decimal_places=9, max_digits=13, null=True),
        ),
        migrations.AlterField(
            model_name='record_data',
            name='magnet_x',
            field=models.DecimalField(decimal_places=9, max_digits=13, null=True),
        ),
        migrations.AlterField(
            model_name='record_data',
            name='magnet_y',
            field=models.DecimalField(decimal_places=9, max_digits=13, null=True),
        ),
        migrations.AlterField(
            model_name='record_data',
            name='magnet_z',
            field=models.DecimalField(decimal_places=9, max_digits=13, null=True),
        ),
    ]
